name: Deploy Medusa Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0 # specify your Terraform version

    - name: Terraform Init
      run: terraform init
      working-directory: terraform # Ensure this matches the location of your Terraform files

    - name: Terraform Plan
      run: terraform plan
      working-directory: terraform # Ensure this matches the location of your Terraform files
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AKIAT7JJVC6EL3H4FP3S}}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.St36/vLK7oxPDTEtN8yQ8lTQvmijjyWXo4cl/hme }}

    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: terraform # Ensure this matches the location of your Terraform files
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AKIAT7JJVC6EL3H4FP3S }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.St36/vLK7oxPDTEtN8yQ8lTQvmijjyWXo4cl/hme }}
