name: Deploy Medusa

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: deploy 

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Ensure full history is fetched

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.0

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform  # Adjust if your .tf files are in a different directory

      - name: Terraform Plan
        run: terraform plan
        working-directory: ./terraform


      - name: Terraform Apply
        run: terraform apply 
        working-directory: ./terraform

